language: ruby

rvm:
  - ruby-head
  - 2.1.2
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.2

branches:
  only:
    - master

gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile